Use semantic release
gravitee-io/gravitee-policy-http-signature pull request #15
Opened 2022-01-20 16:55 UTC by a-cordier

Description
--
Make the project ready for semantic-release 🚀

2022-01-20 16:58 UTC, phiz71 requested changes

2022-01-20 16:58 UTC, phiz71 commented on pom.xml
> +        <publish-folder-path>graviteeio-apim/plugins/policies</publish-folder-path>
Looks like there is a pb with the upgrade script ;)

2022-01-20 21:12 UTC, phiz71 approved these changes

2022-01-21 13:38 UTC, ThibaudAV approved these changes

2022-01-21 13:38 UTC, merged